//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartOne.Engepecas.Warranty.Core.DAO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Hana {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hana() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartOne.Engepecas.Warranty.Core.DAO.Hana", typeof(Hana).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 1 FROM OJDT WHERE &quot;StornoToTr&quot; = {0}.
        /// </summary>
        public static string JournalEntry_IsCancelled {
            get {
                return ResourceManager.GetString("JournalEntry_IsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL SP_WARRANTY_GET(&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, &apos;{3}&apos;, &apos;{4}&apos;).
        /// </summary>
        public static string Warranty_Get {
            get {
                return ResourceManager.GetString("Warranty_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(&quot;U_ENG_GAR_COD&quot;) FROM SCL6.
        /// </summary>
        public static string Warranty_GetMaxCode {
            get {
                return ResourceManager.GetString("Warranty_GetMaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SCL6
        ///SET &quot;U_ENG_GAR_LCM&quot; = {0}
        ///WHERE &quot;SrcvCallID&quot; = {1}
        ///AND &quot;Line&quot; = {2}.
        /// </summary>
        public static string Warranty_UpdateJE {
            get {
                return ResourceManager.GetString("Warranty_UpdateJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SCL6
        ///SET &quot;U_ENG_NC&quot; = &apos;{0}&apos;, 
        ///&quot;U_ENG_Pago&quot; = &apos;{1}&apos;,
        ///&quot;U_ENG_GAR_COD&quot; = {2},
        ///&quot;U_ENG_GAR_DATA&quot; = {3},
        ///&quot;U_ENG_GAR_LCM&quot; = {4},
        ///WHERE &quot;SrcvCallID&quot; = {5}
        ///AND &quot;Line&quot; = {6}.
        /// </summary>
        public static string Warranty_UpdateLine {
            get {
                return ResourceManager.GetString("Warranty_UpdateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        /// &quot;U_BPLId&quot;   &quot;BPLId&quot;,
        /// &quot;U_ContaDebito&quot;  &quot;DebitAccount&quot;,
        /// &quot;U_ContaCredito&quot;  &quot;CreditAccount&quot;
        ///FROM &quot;@ENG_SERV_NC&quot;.
        /// </summary>
        public static string WarrantyConfig_Get {
            get {
                return ResourceManager.GetString("WarrantyConfig_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        /// 	T0.U_ENG_GAR_COD, 	
        /// 	T0.U_ENG_GAR_DATA,
        /// 	T0.U_ENG_GAR_LCM
        /// FROM SCL6 T0
        /// WHERE IFNULL(T0.U_ENG_GAR_COD, 0) &lt;&gt; 0
        ///ORDER BY T0.U_ENG_GAR_COD DESC.
        /// </summary>
        public static string WarrantyNC_FormattedSearch {
            get {
                return ResourceManager.GetString("WarrantyNC_FormattedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL SP_WARRANTY_NC_GET({0}, {1}, {2}).
        /// </summary>
        public static string WarrantyNC_Get {
            get {
                return ResourceManager.GetString("WarrantyNC_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL SP_WARRANTY_NC_QUERY(&apos;{0}&apos;, &apos;{1}&apos;).
        /// </summary>
        public static string WarrantyNC_Query {
            get {
                return ResourceManager.GetString("WarrantyNC_Query", resourceCulture);
            }
        }
    }
}
